### ISSUE TITLE
e2l1 - Dead paratrooper floating with death anim

### ISSUE THREAD

**Issue by ChannelDaniila** [Chrissstrahl/hzm-mohaa-coop-mod#28]
After dieing, paratrooper corpse remains floating at parachute.
[Link for a picture: https://ibb.co/HnzwN53]

**Comment by Chrissstrahl** [comment]
How long does he float there ?
Does he fadeout after 30 sec or a minute or does he stay there ?
Does the same happen in Singleplayer ?

**Comment by ChannelDaniila** [comment]
He disappears like all normal NPC corpses.
No, in singleplayer this guy is hanging down like dead.

**Comment by Chrissstrahl** [comment]
Okay, this could be a issue that would be very difficult to fix.
Since the corpse fades out it is only a cosmetic issue now, and has low priority.

**Comment by 1337Smithy** [comment]
Was able to replicate this before. I put in a fix for friendly.scr, and now can't replicate it anymore. It could have inadvertently fixed this. Needs testing.

**Comment by ChannelDaniila** [comment]
Fixed.

**Comment by 1337Smithy** [comment]
![deadpara](https://user-images.githubusercontent.com/64008963/102781826-35174080-4390-11eb-888e-83bb77bb5ea1.png)
Still happens as confirmed by Channel. Was just a fluke it seems. 

Re-opening.
